export const projectsData = [
  {
    no: 1,
    description: "OFON2 Project Materials (Generator Protection Relays)",
    client: "Totalenergies",
    date: "Jan 2025",
    // location: "Port Harcourt",
    // dateExecuted: "2023",
    status: "On-going",
  },
  {
    no: 2,
    description: "Batteries the LV Micologic Trip Unit & MV Protection Relay",
    client: "Stac-Marine",
    date: "March 2024",
    // location: "Port Harcourt",
    // dateExecuted: "2022",
    status: "COMPLETED",
  },
  {
    no: 3,
    description: "MSWB Re-Certification for BW",
    client: "BW Offshore",
    date: "Sept 2023",
    // location: "Port Harcourt",
    // dateExecuted: "2021",
    status: "Ongoing",
  },
  {
    no: 4,
    description: "Obama Flowstation Plant Process Instrument Upgrade",
    client: "NAOC",
    date: "Oct 2022",
    // location: "Port Harcourt",
    // dateExecuted: "2019",
    status: "Ongoing",
  },
  {
    no: 5,
    description: "PSVs Overhaul & Recertification @ NGC Ajaokuta Gas Plant",
    client: "MORPOL Eng. Services Ltd",
    date: "July 2022",
    // location: "Port Harcourt",
    // dateExecuted: "2018",
    status: "COMPLETED",
  },
  {
    no: 6,
    description: "3.3kv,1C x 70 Sqmm Power Cable Termination Kit for transformer",
    client: "SUDELETTRA",
    date: "June 2022",
    // location: "Port Harcourt",
    // dateExecuted: "2018",
    status: "COMPLETED",
  },
  {
    no: 7,
    description: "Fibre Optic Cable Splicing & Termination",
    client: "SUDELETTRA",
    date: "May 2022",
    // location: "Port Harcourt",
    // dateExecuted: "2018",
    status: "COMPLETED",
  },
  {
    no: 8,
    description: "Subsea Power/Fibre Opti Cable Separation & Glanding & Termination of Power Cable to dedicated Junction Boxes",
    client: "SUDELETTRA",
    date: "April 2022",
    // location: "Port Harcourt",
    // dateExecuted: "2017",
    status: "COMPLETED",
  },
  {
    no: 9,
    description: "Power Cable Termination for Switchgear & Transformer for IKIKE Project at AMENAM (OML 99)",
    client: "SUDELETTRA",
    date: "March 2022",
    // location: "Port Harcourt",
    // dateExecuted: "2016",
    status: "COMPLETED",
  },
  {
    no: 10,
    description: "Supply of 18” Sch 80 API 5L GR. X65 3-Layer PE Coated Line Pipes Augmentation Project.",
    client: "MORPOL Eng. Services Ltd.",
    date: "Nov 2021",
    // location: "Port Harcourt",
    // dateExecuted: "2016",
    status: "COMPLETED",
  },
  {
    no: 11,
    description: "Certification of Pressure Safety Valves For Daramyx Solutions Ltd.",
    client: "Daramyx Solutions Ltd",
    date: "April 2021",
    // location: "Port Harcourt",
    // dateExecuted: "2015",
    status: "COMPLETED",
  },
  {
    no: 12,
    description: "Steam Tracing For NOPL Works at IEFCL (Materials + Labour Services)",
    client: "Morpol Engineering Services Ltd",
    date: "April 2021",
    // location: "Port Harcourt",
    // dateExecuted: "2015",
    status: "COMPLETED",
  },
  {
    no: 13,
    description: "Supply of Stainless Steel Tubing & Swagelok Stainless Steel Fittings",
    client: "MORPOL Eng. Services Ltd.",
    date: "April 2021",
    // location: "Port Harcourt",
    // dateExecuted: "2015",
    status: "COMPLETED",
  },
  {
    no: 14,
    description: "Indorama Gas Metering Integration Detailed Engineering (Process/Piping/Civil/ Structural/Electrical/C&I/HAC/Telecoms)- WPK 3B",
    client: "INDORAMA ELEME PETROCHEMICALS COMPANY",
    date: "Jan 2021",
    // location: "Kolu Ama, Offshore Brass",
    // dateExecuted: "2014",
    status: "COMPLETED",
  },
  {
    no: 15,
    description: "Materials For WT3 (Procurement of PVR Items)",
    client: "EPNL",
    date: "April 2020",
    // location: "NUN RIVERS-SPDC PROJECT",
    // dateExecuted: "2013",
    status: "COMPLETED",
  },
  {
    no: 16,
    description: "OML 58 – Materials For Obite Early Condensate Spiking Project	",
    client: "EPNL",
    date: "April  2019",
    // location: "FPSO Oyo field offshore Lagos",
    // dateExecuted: "2013",
    status: "COMPLETED",
  },
];
